Show names of missing resources if they can not be found
As opposed to a null ptr exception

[error] (run-main) java.lang.NullPointerException
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
	at scala.io.BufferedSource.reader(BufferedSource.scala:22)
	at scala.io.BufferedSource.bufferedReader(BufferedSource.scala:23)
	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader(BufferedSource.scala:33)
	at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(BufferedSource.scala:38)
	at scala.io.Codec.wrap(Codec.scala:64)
	at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
	at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
	at scala.collection.Iterator$$anon$14.next(Iterator.scala:148)
	at scala.collection.Iterator$$anon$25.hasNext(Iterator.scala:463)
	at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:334)
	at scala.io.Source.hasNext(Source.scala:238)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.io.Source.foreach(Source.scala:181)
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:285)
	at scala.io.Source.addString(Source.scala:181)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:263)
	at scala.io.Source.mkString(Source.scala:181)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:265)
	at scala.io.Source.mkString(Source.scala:181)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:267)
	at scala.io.Source.mkString(Source.scala:181)
	at com.wordnik.swagger.codegen.Codegen$$anonfun$writeSupportingClasses$1.apply(Codegen.scala:381)
	at com.wordnik.swagger.codegen.Codegen$$anonfun$writeSupportingClasses$1.apply(Codegen.scala:367)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:45)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
	at scala.collection.immutable.List.map(List.scala:45)
	at com.wordnik.swagger.codegen.Codegen.writeSupportingClasses(Codegen.scala:367)
	at com.wordnik.swagger.codegen.BasicGenerator.generateClient(BasicGenerator.scala:128)
	at com.xeralux.codegen.ScalaXeraluxCodegen$.main(PythonXeraluxCodegen.scala:14)
	at com.xeralux.codegen.ScalaXeraluxCodegen.main(PythonXeraluxCodegen.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
java.lang.RuntimeException: Nonzero exit code: 1