[Python]: correct query_params type.
query_params is a list of tuple, so defined it as a list by
default instead of a dict.

This fix below issue on the client side.

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    api_response = api_instance.seek("the")
  File "python-client/swagger_client/apis/seek_api.py", line 168, in seek
    (data) = self.seek_with_http_info(recherche, **kwargs)
  File "python-client/swagger_client/apis/seek_api.py", line 245, in seek_with_http_info
    collection_formats=collection_formats)
  File "python-client/swagger_client/api_client.py", line 323, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "python-client/swagger_client/api_client.py", line 135, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "python-client/swagger_client/api_client.py", line 512, in update_params_for_auth
    querys.append((auth_setting['key'], auth_setting['value']))
AttributeError: 'dict' object has no attribute 'append'

Signed-off-by: Gregory Herrero <gregory.herrero@gmail.com>