Fix Typescript errors with 'strictNullChecks' mode enabled error TS2454: Variable 'contentTypeHeader' is used before being assigned. error TS2345: Argument of type 'FetchAPI | undefined' is not assignable to parameter of type 'FetchAPI'.